# Generated by Django 2.1 on 2020-02-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authour',
            new_name='author',
        ),
    ]
